<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_PILIH</name>
   <tag></tag>
   <elementGuidId>199cbda7-c115-4d26-bd34-7b5ab131e7cb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.btn.btn-light.button-daftar.mb-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@type='button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>71582216-9a2a-453d-b3c0-b5e3559b1e5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c09f2f7d-a3c9-45d7-80ee-812fa6e5059a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>selectIntegration('AWHRUBY')</value>
      <webElementGuid>6557a621-738e-407f-832c-21b40e41a3f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-light button-daftar mb-2</value>
      <webElementGuid>185cb5ee-a201-4cf2-9977-a2069e405cee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PILIH</value>
      <webElementGuid>db5798ad-bcd3-4f24-a7ee-3046683e0d8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;splide01-slide01&quot;)/div[@class=&quot;card mt-3 mb-2 mr-2&quot;]/div[@class=&quot;d-flex justify-content-center&quot;]/div[@class=&quot;btn btn-light button-daftar mb-2&quot;]</value>
      <webElementGuid>d1b7e616-5383-45c2-8e73-512c0b6e26e3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@type='button']</value>
      <webElementGuid>4023f35e-7120-498b-b299-68ab9a782e33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='splide01-slide01']/div/div[2]/div</value>
      <webElementGuid>8f2f7cb9-600f-4fd5-ba20-fa0c22b816db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Silahkan Pilih Integrasi'])[1]/following::div[10]</value>
      <webElementGuid>2d65765a-79ab-4223-bdd2-23b568e86711</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='PILIH']/parent::*</value>
      <webElementGuid>4c3c2751-37dd-4f91-87f8-e40b7fcfcff2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div[2]/div</value>
      <webElementGuid>3e47e018-fbfa-4028-96ff-6ac9be5f1efc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@type = 'button' and (text() = 'PILIH' or . = 'PILIH')]</value>
      <webElementGuid>6f9769af-692d-48cc-94f5-861b243995ac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
