<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Silahkan Pilih Services_card-body</name>
   <tag></tag>
   <elementGuidId>12b1fa31-e314-4c37-8934-2211fec8a238</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.card-body</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='splide01-slide01']/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>df652815-bd9a-4ba7-bfbf-29d0a6249da2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card-body</value>
      <webElementGuid>ed811d07-28f4-4bc3-9df7-8ae42a29544b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;splide01-slide01&quot;)/div[@class=&quot;card mr-2 mb-2 card-service&quot;]/div[@class=&quot;card-body&quot;]</value>
      <webElementGuid>8fd36dfa-97b7-4832-8a88-e808f551758b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='splide01-slide01']/div/div</value>
      <webElementGuid>0d2b24fc-b9ec-4248-9280-eef4764b8075</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Silahkan Pilih Services'])[1]/following::div[10]</value>
      <webElementGuid>57c14c16-9c26-4a5d-9a4f-505d5b18d967</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/div/div</value>
      <webElementGuid>a1769c48-05d3-4045-9b77-00f90cd3980d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
