<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Form input kode tiket</name>
   <tag></tag>
   <elementGuidId>6bf0eb0f-1ce8-405e-893d-0c33048a7e3c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#guestUniqueCode</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='guestUniqueCode']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9d261aad-a543-4929-bc5d-e8c770cdf962</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7a511b8d-5cca-4983-ab4f-083b93d1580d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>guestUniqueCode</value>
      <webElementGuid>92def256-42c8-4355-ad4d-3f9ed810a3b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;guestUniqueCode&quot;)</value>
      <webElementGuid>9729edaf-6810-4d1c-ab25-2b4b919b201f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='guestUniqueCode']</value>
      <webElementGuid>40b34b8e-9533-404f-930f-2cb77b404735</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='inputCode']/div/div/div/div/input</value>
      <webElementGuid>7062731a-3ec7-4c48-ab29-fbf466b33db7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/input</value>
      <webElementGuid>9e2775cb-3c96-4567-b77a-9b600fbbb416</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'guestUniqueCode']</value>
      <webElementGuid>71703588-b157-470e-b412-4ae5fc4fe91c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
