<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Tombol input kode tiket pickup</name>
   <tag></tag>
   <elementGuidId>7d281861-f35e-415b-811d-5e0d48a35a5a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>db39c736-65b5-45fc-97b4-40454ddbde85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>bfcb6f92-96c9-48c5-bdd1-2f3df8973b66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>inputCode()</value>
      <webElementGuid>5e905ef6-23b3-4825-aa06-42a8d5320279</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary w-100</value>
      <webElementGuid>3f154b4f-1c99-4d6b-8715-a1defdb3d8f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Masukan Kode</value>
      <webElementGuid>ea95ace1-838e-4493-b16b-bc71bd60b463</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;container-scroller&quot;]/div[@class=&quot;container-fluid page-body-wrapper&quot;]/div[@class=&quot;main-panel pt-3 px-4&quot;]/div[@class=&quot;row g-0 flex-column-reverse justify-content-center align-items-center mb-5&quot;]/div[@class=&quot;col-lg-6 wow fadeIn&quot;]/div[@class=&quot;row g-12 isi-content w-100 m-auto&quot;]/div[@class=&quot;col-sm-12&quot;]/div[@class=&quot;text-center row g-3 p-3 justify-content-center&quot;]/div[@class=&quot;col-6&quot;]/button[@class=&quot;btn btn-primary w-100&quot;]</value>
      <webElementGuid>c1dbbed0-c4d0-4136-8f33-9b9f7424b128</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[2]</value>
      <webElementGuid>7bf38dae-817e-4e20-bfee-93fa70d96ada</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Scan QR'])[1]/following::button[1]</value>
      <webElementGuid>e3c2a4a6-7374-4536-8cb9-deb491db6249</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WELCOME DRINK'])[1]/following::button[2]</value>
      <webElementGuid>c7992b81-758c-41e7-847c-e1464decba81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Laporan Harian'])[1]/preceding::button[1]</value>
      <webElementGuid>ab81d1c9-dbc4-4019-b524-c264d27ed126</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Masukan Kode']/parent::*</value>
      <webElementGuid>063ab8bb-568d-444b-9b16-466939085ae7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>0d6004c7-5236-46c7-858c-93ffe82b21e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Masukan Kode' or . = 'Masukan Kode')]</value>
      <webElementGuid>427810ac-efe7-4704-b36f-fcb1df085cf3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
