<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>add_photobooth</name>
   <tag></tag>
   <elementGuidId>b5dcdbc8-5bb4-43f7-8fa9-898f943ce3f0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='select-room-section']/div/div[2]/div[3]/div[2]/div/div/div/div[2]/div/div[7]/div/div[3]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.plus-sign</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>1fb5d9c3-a7f9-4648-b294-290771af5a02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>plus-sign</value>
      <webElementGuid>1cb44f08-a4c2-4161-b5ad-7305358a7570</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>+</value>
      <webElementGuid>9994ef5e-4f28-4441-9a7d-905c98c870ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select-room-section&quot;)/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;col-lg-10 col-md-10 col-10 center-block mt-3&quot;]/div[@class=&quot;row mt-3&quot;]/div[@class=&quot;col-12 text-center menu&quot;]/div[@class=&quot;device-package&quot;]/div[@class=&quot;card mb-3 mr-2&quot;]/div[@class=&quot;row no-gutters&quot;]/div[@class=&quot;col-6&quot;]/div[@class=&quot;card-body d-flex flex-column p-2&quot;]/div[@class=&quot;toogle-wrapper&quot;]/div[@class=&quot;toogle-cart mr-2&quot;]/div[@class=&quot;squire plus addtocart&quot;]/span[@class=&quot;plus-sign&quot;]</value>
      <webElementGuid>ceedcb38-ac19-499b-94e4-709ea826786a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='select-room-section']/div/div[2]/div[3]/div[2]/div/div/div/div[2]/div/div[7]/div/div[3]/span</value>
      <webElementGuid>4455bb5f-1e5a-40ce-824b-e35b7ec75aaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[1]/following::span[1]</value>
      <webElementGuid>6dd0fcc6-b9a7-4050-b09d-3d448fd4e77b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Basic'])[1]/preceding::span[2]</value>
      <webElementGuid>e85b8d84-7d07-4842-81f2-dc8f0fb67f76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='+']/parent::*</value>
      <webElementGuid>9fec2a87-3cdc-42c2-beba-cdf4c8641efc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div[3]/span</value>
      <webElementGuid>661c7861-e93d-4418-8bc9-6e13bfa2069c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '+' or . = '+')]</value>
      <webElementGuid>9cd275e3-6fff-48e9-aa31-162fcaa2ec12</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
