<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Tombol halaman users</name>
   <tag></tag>
   <elementGuidId>16c1149b-bd50-4170-b9bc-5c847142e30f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#loadUsers</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='loadUsers']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e7ccf65f-1a48-4cb9-8af2-3386a0edef83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link btn-tab</value>
      <webElementGuid>a36f21a3-d830-4538-ba47-d378083358fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>31c7078c-45a1-425b-b98c-54477a1cab8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#users</value>
      <webElementGuid>aaf76655-a5a6-4128-99c1-f60a78d8e2e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>loadUsers</value>
      <webElementGuid>db123eaf-8a71-46b9-a6c3-c24d5114e649</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Users</value>
      <webElementGuid>7cd030a7-d92f-4fed-93cc-01c1744e26a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;loadUsers&quot;)</value>
      <webElementGuid>8e0e1afa-e2fa-4098-aeed-f6f2e8932c45</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='loadUsers']</value>
      <webElementGuid>2d0fbc25-2ceb-47b6-a87b-eb65c7715b66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Users')]</value>
      <webElementGuid>3ca6f46d-62a8-4407-b4c8-0c6bb2417a01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kehadiran'])[1]/following::a[1]</value>
      <webElementGuid>0f7183e2-e5e7-4361-a187-fadb62a7ec79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Data Tamu'])[1]/following::a[2]</value>
      <webElementGuid>85471c8e-5618-4985-8118-7938804111e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Data Tamu Telkom University Sabtu Sesi 1'])[1]/preceding::a[1]</value>
      <webElementGuid>61fba3af-8985-4681-b0c1-cfc79964de8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Users']/parent::*</value>
      <webElementGuid>02825129-c955-4c40-9cad-de81fd7213d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#users')]</value>
      <webElementGuid>99148661-5548-4947-aa91-0b57d448c360</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul/li[3]/a</value>
      <webElementGuid>bd1cba30-930c-4833-af91-0157b6bdfbcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#users' and @id = 'loadUsers' and (text() = 'Users' or . = 'Users')]</value>
      <webElementGuid>085c1b17-2bdb-454f-964a-7d8412e41e2c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
