<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Selanjutnya</name>
   <tag></tag>
   <elementGuidId>6c71e64f-21db-4c92-98da-6b2861b328ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@onclick='validateForm()']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-primary.custom-btn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2d2f8b8d-fe82-4fda-bfc6-5f7b296ca5b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>validateForm()</value>
      <webElementGuid>c5ddc1e8-c80f-4bfc-b808-30a15033ac89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary custom-btn</value>
      <webElementGuid>bdfcd025-540e-435d-937b-5ae71380b61b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Selanjutnya</value>
      <webElementGuid>b848be04-2778-4c36-a7e5-1327e1e60b0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;data-diri&quot;)/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row d-flex justify-content-center&quot;]/div[@class=&quot;container d-flex justify-content-center align-items-center min-vh-100&quot;]/div[@class=&quot;card&quot;]/div[@class=&quot;card-body&quot;]/div[@class=&quot;d-flex justify-content-center&quot;]/button[@class=&quot;btn btn-primary custom-btn&quot;]</value>
      <webElementGuid>991d0d50-c2e9-4df6-8cfd-145b4010dc26</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@onclick='validateForm()']</value>
      <webElementGuid>c1079724-2656-4c52-98bc-b7622ecebfe8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='data-diri']/div/div[2]/div[2]/div/div/div[3]/button[2]</value>
      <webElementGuid>0757aa3c-7020-44f2-84d5-f59e2d0f27f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Batalkan Order'])[1]/following::button[1]</value>
      <webElementGuid>81928ce9-a89b-49d7-b3dd-20d11511675c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Isi Data Diri Ya!'])[2]/following::button[2]</value>
      <webElementGuid>9324bd33-0dc9-43be-b5c4-c5f41dccb974</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Selanjutnya']/parent::*</value>
      <webElementGuid>51c81360-366c-4537-9960-5460e10fc617</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>77d20621-ebea-4628-b26e-1e59b76f220f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Selanjutnya' or . = 'Selanjutnya')]</value>
      <webElementGuid>572cddce-f2ad-494a-9ce0-e30c52d109de</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
