<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Apply</name>
   <tag></tag>
   <elementGuidId>fd63b032-f030-452a-aad4-b5ad9ee5ef25</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[contains(@class, 'apply-voucher-btn')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-warning.col-3.ml-2.mt-3.apply-voucher-btn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>32faf710-4196-4a49-972d-077b0d143418</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-warning col-3 ml-2 mt-3 apply-voucher-btn</value>
      <webElementGuid>ce007967-ad96-4cdb-87ab-87f9906d681c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-service-id</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>87d6c0ff-0757-4c8b-b857-d125993ca5eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Apply</value>
      <webElementGuid>8e4a3737-e289-463b-b755-bc09b772d2dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;order-details&quot;)/div[@class=&quot;card&quot;]/div[@class=&quot;card-body&quot;]/div[@class=&quot;align-items-center row&quot;]/button[@class=&quot;btn btn-warning col-3 ml-2 mt-3 apply-voucher-btn&quot;]</value>
      <webElementGuid>1237b197-331b-40f3-810b-0f33c7c49d47</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='order-details']/div/div/div[2]/button</value>
      <webElementGuid>ba77277c-c41d-4bbc-bf95-071df69bea64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Serius Kopi'])[1]/following::button[1]</value>
      <webElementGuid>65c6e7a5-884d-4c10-847a-01f9b685c7c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AWH Mini Cafe'])[1]/following::button[1]</value>
      <webElementGuid>7fd57c3d-b69e-46e5-8b3a-1e77e2554962</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ringkasan Pembayaran'])[1]/preceding::button[1]</value>
      <webElementGuid>a0114e6c-bf7a-4380-9fb1-67f8cb8a478b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bayar Sekarang'])[1]/preceding::button[1]</value>
      <webElementGuid>b483ba8f-d3c2-468e-8f89-74a083186b0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Apply']/parent::*</value>
      <webElementGuid>04d95183-2985-4798-b51c-73a22c38c623</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>bea5a376-f873-4595-a967-74048ad2089b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Apply' or . = 'Apply')]</value>
      <webElementGuid>e3b5d883-fa16-4346-96aa-81979c894b95</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
