<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Tambah Pesanan</name>
   <tag></tag>
   <elementGuidId>b3d4cae6-a2fe-46b2-9ee1-0a46626d68cc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@onclick='TambahPesanan()']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.btn.btn-success.w-100</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a4c556ac-0c13-4a6f-8c6e-61ca64977500</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-success w-100</value>
      <webElementGuid>eb806db4-768f-4126-9bbc-66dd5d840e7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>TambahPesanan()</value>
      <webElementGuid>795284e1-4635-4481-a061-93d68f90aa77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tambah Pesanan</value>
      <webElementGuid>0c2c229c-a8d8-4a2c-a7de-34462f570975</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;bg-image p-4&quot;]/div[@class=&quot;row d-flex justify-content-center&quot;]/div[@class=&quot;col-lg-10 col-md-10 col-10 center-block&quot;]/div[@class=&quot;row scroll2&quot;]/div[@class=&quot;col-lg-6 col-md-6 col-12 mt-2&quot;]/div[@class=&quot;d-flex justify-content-between mt-2&quot;]/div[@class=&quot;btn btn-success w-100&quot;]</value>
      <webElementGuid>1af64013-0578-41e4-b466-c227740be87c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@onclick='TambahPesanan()']</value>
      <webElementGuid>15c71b96-9da4-4931-afc0-b791b2038730</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Batalkan Order'])[1]/following::div[1]</value>
      <webElementGuid>13a8d63f-ba22-4e4b-856f-04d27bf9f10b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bayar Sekarang'])[1]/following::div[3]</value>
      <webElementGuid>8ea93703-cb63-4fd3-8935-6b33bd504656</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Tambah Pesanan']/parent::*</value>
      <webElementGuid>5be99163-a5db-4235-b4ce-75cbfa8b12a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]/div[2]</value>
      <webElementGuid>6004864c-08b4-4792-adf5-ae8218116f1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Tambah Pesanan' or . = 'Tambah Pesanan')]</value>
      <webElementGuid>5fa6581b-66d3-4f69-8fff-eaf2c059c54a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
