<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Dropdown Jenis Undangan</name>
   <tag></tag>
   <elementGuidId>e95c4bbf-d408-41eb-91aa-4bd99ec7c4a0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='Undangan']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Undangan</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>e9246fe0-49ce-4220-a08d-95da1baf473f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>598cd498-846f-4a35-bc1d-d516bd02e39c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Undangan</value>
      <webElementGuid>cf50b674-0782-4a31-a5ad-cebcf1bc89c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Undangan</value>
      <webElementGuid>737f596f-9c66-4349-8cf2-b9331791defc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                            BIASA
                            VIP
                            EKSTRA
                            VVIP
                        </value>
      <webElementGuid>4f06524d-a39e-4d9c-bbdc-71b862a37d7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;addTamuForm&quot;)/div[@class=&quot;form-group&quot;]/select[@id=&quot;Undangan&quot;]</value>
      <webElementGuid>6374711c-a71c-4bcb-87c9-dde924e52b7c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='Undangan']</value>
      <webElementGuid>8181dd6a-e1bf-44e6-8fda-5b37f035fee5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='addTamuForm']/div[4]/select</value>
      <webElementGuid>51bbd197-9cef-4934-8d1c-6c2cbf5b1a13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jenis Undangan'])[2]/following::select[1]</value>
      <webElementGuid>6f234fc4-d564-44d8-a3df-378a1a305cbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No Telepon'])[2]/following::select[1]</value>
      <webElementGuid>f343036e-093d-4912-9fd3-ca8d29455a95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Personal'])[2]/preceding::select[1]</value>
      <webElementGuid>701d98c5-6c4e-4e69-a55c-459b5488ef30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Group'])[2]/preceding::select[1]</value>
      <webElementGuid>65b386a5-9e30-4690-b58f-76252bcb368a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[4]/select</value>
      <webElementGuid>7a269198-a577-40b7-b1fe-df499185c49b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'Undangan' and @id = 'Undangan' and (text() = '
                            BIASA
                            VIP
                            EKSTRA
                            VVIP
                        ' or . = '
                            BIASA
                            VIP
                            EKSTRA
                            VVIP
                        ')]</value>
      <webElementGuid>8522e06b-ddc6-46b1-bd4b-26e17895ecf5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
