<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Form Input Alamat Tamu</name>
   <tag></tag>
   <elementGuidId>7bd05bf1-c17e-40a6-826f-32953641eac7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='Alamat']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Alamat</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>99c1a469-52b4-44a0-ad4c-2e91c3ad1b39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>f9aeb0b6-ac31-471b-9715-add697d31139</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>5e32a0d2-5f8d-4c71-b6f5-6b2ece919b08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Alamat</value>
      <webElementGuid>af142def-a015-4676-9466-f3b176e73afc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Alamat</value>
      <webElementGuid>12dfd9cb-64c8-41dd-a976-30daf7815395</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>93ed68b9-69bc-4468-b526-aa5880a412ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;addTamuForm&quot;)/div[@class=&quot;form-group&quot;]/textarea[@id=&quot;Alamat&quot;]</value>
      <webElementGuid>15348595-3cf5-4c96-99ee-ddde2841c7f5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='Alamat']</value>
      <webElementGuid>3210c1d2-ead1-4e74-846e-2c3bd38d7cc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='addTamuForm']/div[2]/textarea</value>
      <webElementGuid>833fef3d-b0e2-4fc2-bec2-2e8565101109</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/textarea</value>
      <webElementGuid>45ad3c83-a98d-4c02-8a3d-9589996258a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'Alamat' and @name = 'Alamat']</value>
      <webElementGuid>a7159cea-b516-4cda-b7cd-a6711e6b18bf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
