<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Form Pencarian Data Tamu</name>
   <tag></tag>
   <elementGuidId>0cd9c7d3-00c4-49da-80d0-ba1b5d8a31aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#live-search</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='live-search']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5709b616-6711-403f-8d75-dd202379a6af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>live-search</value>
      <webElementGuid>ee27a8b0-144c-4e95-9102-640dd327b85d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-1</value>
      <webElementGuid>5da571b3-c79b-4ab0-84de-6c9d9bc47d55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c173a95c-7913-47cf-83f8-9d9b9ba0c647</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search..</value>
      <webElementGuid>b8f00d16-4f27-4459-9958-4a1f010a2ae1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>liveSearchName()</value>
      <webElementGuid>61b84694-8f57-4150-945d-b6d09e4320f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;live-search&quot;)</value>
      <webElementGuid>139163f9-d8d4-42ad-8bfb-0e7908da9cb6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='live-search']</value>
      <webElementGuid>9f27a173-e92a-4b37-aac8-92388a9b3a4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='data-tamu']/div/div/div/input</value>
      <webElementGuid>60b1e152-517e-4c28-a629-8ccfbb91c85c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/input</value>
      <webElementGuid>d03d4ecb-87e1-4c0e-9023-ee4fb4321058</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'live-search' and @type = 'text' and @placeholder = 'Search..']</value>
      <webElementGuid>fb1dffc1-4f2c-475a-98a5-8cec5d2c7986</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
