<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Form Input Nama Tamu</name>
   <tag></tag>
   <elementGuidId>43a972b8-a113-46a5-9e2e-9078074059cf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='nama'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#addTamuForm > div.form-group > #nama</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f8a3ccc6-27ad-404d-934b-a30e138c9110</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bdbebc73-661d-46ea-96c9-75c27ece12d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nama</value>
      <webElementGuid>7e2bba8a-d9c5-4126-8a39-3f23cbf8faf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Nama</value>
      <webElementGuid>9c7fde36-db77-4bd3-a30d-2d7d2ae949ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>43c4e056-a99e-44a7-b50c-c2efd15a0a4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;addTamuForm&quot;)/div[@class=&quot;form-group&quot;]/input[@id=&quot;nama&quot;]</value>
      <webElementGuid>38a2240c-1167-4207-9c5b-aba121ee2277</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='nama'])[2]</value>
      <webElementGuid>684e8127-913b-43f0-891d-86d0e96352a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='addTamuForm']/div/input</value>
      <webElementGuid>58fe1d78-f536-46f6-8edf-dd6f13463d6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]/form/div/input</value>
      <webElementGuid>0d6a99b3-59a1-45e6-ae83-c37f60450ad0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'nama' and @name = 'Nama']</value>
      <webElementGuid>59eaca3f-64dc-4aa8-b9b1-8977ecbfc03e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
