<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iForm Input No Telpn Tamu</name>
   <tag></tag>
   <elementGuidId>95d7f59b-9bc0-444b-bfaa-19b27e5e3ba9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Telepon']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Telepon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bfab0bd3-51b0-4329-a4de-b8a5cbb9201e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>83306669-c92e-402e-9d12-9c02d49f5853</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Telepon</value>
      <webElementGuid>b72e47f3-08c0-4423-93c4-e577e6c248b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Telepon</value>
      <webElementGuid>b0db215a-09e4-47a7-8134-e3a5c28f6874</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>ff0fe662-7434-4185-8b1e-141d92b56d84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>limitInput(this)</value>
      <webElementGuid>bf1d82cc-55d9-459b-a3a7-fd3c6f515cd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;addTamuForm&quot;)/div[@class=&quot;form-group&quot;]/input[@id=&quot;Telepon&quot;]</value>
      <webElementGuid>000695fc-ffeb-450f-a6ef-3128c7260cf4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Telepon']</value>
      <webElementGuid>81c4b06c-6be4-4197-bd40-64da7b693c2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='addTamuForm']/div[3]/input</value>
      <webElementGuid>c75bbd9e-7b53-44c6-854e-decf64ce6554</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[3]/input</value>
      <webElementGuid>f7180a1a-5d1e-46ae-a636-dfa9bebbdc57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'Telepon' and @name = 'Telepon']</value>
      <webElementGuid>2b35544b-8a40-4358-8484-ef97a47ce2f6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
