<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Tombol Hapus Data Tamu</name>
   <tag></tag>
   <elementGuidId>d4b2305d-42d2-4ab3-8c43-180b8ce4d0cb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Hapus')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.dropdown-item.btn-primary.edit-tamu-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>92cff958-a9db-4cae-b71a-8bd49a693c9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>deleteTamuUndangan('1740365451864', '76144')</value>
      <webElementGuid>2803da3e-5f2a-46c6-a9c3-d7175af2662c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-item btn-primary edit-tamu-button</value>
      <webElementGuid>6534a3ac-767c-458e-b2f1-11509eb86a26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hapus</value>
      <webElementGuid>d5022b32-5094-4846-a8e8-b68415e507e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;data-tamu&quot;)/div[@class=&quot;data-container&quot;]/ul[@class=&quot;data-container__list data-list&quot;]/li[@class=&quot;tableItem&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-5 col-lg-6 justify-content-end justify-content-lg-end align-items-center text-center d-flex px-0&quot;]/div[@class=&quot;dropdown show&quot;]/div[@class=&quot;dropdown-menu dropdown-menu-right show&quot;]/a[@class=&quot;dropdown-item btn-primary edit-tamu-button&quot;]</value>
      <webElementGuid>807c1a0f-c535-497a-8741-a5b604b90f16</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick=&quot;deleteTamuUndangan('1740365451864', '76144')&quot;]</value>
      <webElementGuid>0699f882-cb44-4b19-984c-78b7f017d0f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='data-tamu']/div[2]/ul/li/div/div/div[2]/div[3]/div/a</value>
      <webElementGuid>58caef35-2707-43ce-9869-144756ae11fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Hapus')]</value>
      <webElementGuid>d7ff740f-ada1-4c5f-b26b-2bf7bbb3acfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Anda Sudah Mengirim Whatsapp'])[1]/following::a[1]</value>
      <webElementGuid>8f61f94e-83e1-41de-8161-a7fba8558ab5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='&lt;'])[1]/preceding::a[1]</value>
      <webElementGuid>d7397bbf-d5df-4485-972a-45ef417afe45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='>'])[1]/preceding::a[1]</value>
      <webElementGuid>a38d9f9d-dfdc-404d-8ee3-3c0890d0a9a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Hapus']/parent::*</value>
      <webElementGuid>723dae57-c79a-4cfc-a210-68878722c732</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/a</value>
      <webElementGuid>842b9e16-e0f9-403c-ad4b-4e24ee14ce2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'Hapus' or . = 'Hapus')]</value>
      <webElementGuid>080d13d7-30ab-4bda-b76d-ee830a5198c6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
