<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Tombol Input Grup Edit</name>
   <tag></tag>
   <elementGuidId>1702bf93-bff2-4d78-b706-7cd18c5d2346</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='nos-2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#nos-2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>94ec7197-4e22-46da-bf2e-69a68bbc1e87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nos-2</value>
      <webElementGuid>6ef77c82-9c7c-4f59-999b-30f0196a01a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>number-of-stuffs</value>
      <webElementGuid>2c0fac08-8f15-4366-8f4f-82fe813d917f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>974cba83-b481-4310-9912-04cebd6ed35a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Group</value>
      <webElementGuid>eebbc1c9-fd6f-423c-97c2-0f0543144616</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;group-radio&quot;)/input[@id=&quot;nos-2&quot;]</value>
      <webElementGuid>c162872f-60ef-44c2-9a55-d80aa4b1749c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nos-2']</value>
      <webElementGuid>deb9250b-a5b1-467d-81e0-8e8001073c42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='group-radio']/input[2]</value>
      <webElementGuid>f2c79a6a-4b82-475d-bafa-3c6422d0c602</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/input[2]</value>
      <webElementGuid>2aa6a7bb-cf93-4db9-84e8-2adedbafa9af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'nos-2' and @name = 'number-of-stuffs' and @type = 'radio']</value>
      <webElementGuid>845de476-ccff-475d-a2cf-177347fc38dd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
