<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Tombol Jenis Tiket Edit</name>
   <tag></tag>
   <elementGuidId>01b0dc7b-fe9a-497d-8c14-57a1b18e3181</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='TipeUndangan']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#TipeUndangan</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>dce71347-5810-423d-953e-2e86569c4d8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>aecf4383-bbdc-4b58-8b30-e725d3717646</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TipeUndangan</value>
      <webElementGuid>7970f343-7fe6-4c75-a710-dc9e746ac699</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Undangan</value>
      <webElementGuid>8c0814c1-e895-4672-a6a4-03ac52ee548c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        BIASA
                        VIP
                        EKSTRA
                        VVIP
                    </value>
      <webElementGuid>b7b81d0c-721b-46e9-893c-c30d8c050113</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TipeUndangan&quot;)</value>
      <webElementGuid>68963509-32a7-4d8b-92d6-83e223955706</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='TipeUndangan']</value>
      <webElementGuid>006ac799-c9f5-41b8-8f1d-7f536c187cf2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-tamu-edit']/div/div/div[2]/div[4]/select</value>
      <webElementGuid>772ca5d4-cf32-4612-ae03-623971171bb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jenis Undangan'])[1]/following::select[1]</value>
      <webElementGuid>1ef703ff-885f-480f-8d1d-f8394eb04202</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No Telepon'])[1]/following::select[1]</value>
      <webElementGuid>e239f989-6742-47a1-a966-9df451b36c7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Personal'])[1]/preceding::select[1]</value>
      <webElementGuid>50285bc9-7bc7-40a8-9d54-1290e953415e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Group'])[1]/preceding::select[1]</value>
      <webElementGuid>5b70ee16-36b2-4db7-b163-86a8a73f2e9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>01f76919-5644-4ce5-9fdb-7b4463948191</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'TipeUndangan' and @name = 'Undangan' and (text() = '
                        BIASA
                        VIP
                        EKSTRA
                        VVIP
                    ' or . = '
                        BIASA
                        VIP
                        EKSTRA
                        VVIP
                    ')]</value>
      <webElementGuid>87dccc3e-00c1-4b1f-a463-773be734e145</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
