<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Tombol Kelola Data Tamu</name>
   <tag></tag>
   <elementGuidId>78ca7030-1116-488a-b337-d6049dc16c29</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='data-tamu']/div[2]/ul/li/div/div/div[2]/div[3]/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.img-click.dropdown-toggle.icon-mobile</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>e196241a-55c4-4600-a3e8-e0bdc52e2421</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://dev.awh.co.id/area-undangan/assets/images/dashboard/icon/more-2.png</value>
      <webElementGuid>90e682af-8d03-496e-a1f3-dec422b51818</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>d4063dc3-6928-4d44-96ed-a11d62705635</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>53e1a2ad-56f7-4fac-b6fd-809f3c319f2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>icon</value>
      <webElementGuid>4a9ab931-c551-4219-9ddf-92c97ae9a3bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-click dropdown-toggle icon-mobile</value>
      <webElementGuid>4cfda9e2-a5a1-4594-9ae6-68f87d5f5cd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>dropdown</value>
      <webElementGuid>df3ee1a5-ad59-4049-abc9-3ea8d31b9686</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>09cb433b-4bc7-4e9c-970c-0a49e05eeaeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b634d89e-1d72-42f8-9f97-8a33400705f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-display</name>
      <type>Main</type>
      <value>static</value>
      <webElementGuid>97d3b161-f2f1-4dc4-822a-fd5c077f93e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;data-tamu&quot;)/div[@class=&quot;data-container&quot;]/ul[@class=&quot;data-container__list data-list&quot;]/li[@class=&quot;tableItem&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-5 col-lg-6 justify-content-end justify-content-lg-end align-items-center text-center d-flex px-0&quot;]/div[@class=&quot;dropdown&quot;]/img[@class=&quot;img-click dropdown-toggle icon-mobile&quot;]</value>
      <webElementGuid>7661c79f-7ad6-41b7-9fd5-c319ad944928</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='data-tamu']/div[2]/ul/li/div/div/div[2]/div[3]/img</value>
      <webElementGuid>d65b3ed3-c615-4979-8ff9-a215da6cf29c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='icon'])[2]</value>
      <webElementGuid>2fa56954-9c4c-4376-afb5-598557964d11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/img</value>
      <webElementGuid>cd7df2cf-4f1c-43a3-af6b-7ff9cfd39064</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://dev.awh.co.id/area-undangan/assets/images/dashboard/icon/more-2.png' and @alt = 'icon']</value>
      <webElementGuid>a487a1ed-aa56-425e-af38-745b988b35d5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
