<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Tombol Input Undangan Individu</name>
   <tag></tag>
   <elementGuidId>b1c032d8-2db8-44ab-83aa-e54d3a6d0f38</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='nos-1'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#addTamuForm > div.form-group > #nos-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1c4fb035-749c-40f1-bd54-911603caa344</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nos-1</value>
      <webElementGuid>b11be278-4fbd-4d50-a6ae-3524f68fa077</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>number-of-stuffs</value>
      <webElementGuid>3287ca17-3d33-42d3-bb22-5a9eadf977d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>1fd8270d-4653-42d2-80b9-b633643de716</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Personal</value>
      <webElementGuid>a0d39011-559e-4fb3-8924-0a8fe64f09c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;addTamuForm&quot;)/div[@class=&quot;form-group&quot;]/input[@id=&quot;nos-1&quot;]</value>
      <webElementGuid>dacf4b08-0f80-464e-a864-47c212b93ed0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='nos-1'])[2]</value>
      <webElementGuid>11559d4f-69dc-4e27-ada9-732ac1008c2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='addTamuForm']/div[5]/input</value>
      <webElementGuid>26b56c9f-700d-436b-aa43-7a44674fbf8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[5]/input</value>
      <webElementGuid>9e26d0b5-e68f-4e7b-bc6e-788a8cc576d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'nos-1' and @name = 'number-of-stuffs' and @type = 'radio']</value>
      <webElementGuid>a6a8e1ad-f0a0-4075-93c8-fb9d3976d3d3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
