<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Isi Data Diri Ya_no_handphone</name>
   <tag></tag>
   <elementGuidId>28ffb13b-4079-48f1-b391-05572d431e1f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#no_handphone</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='no_handphone']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a5e8463b-c142-4256-8ccc-f1da0d5136ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>no_handphone</value>
      <webElementGuid>c36765bf-356d-4dbd-8809-21755d6ddacf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d76f3779-fa29-4ad6-9904-963f3b5fd5e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control text-center p-2</value>
      <webElementGuid>4b51d22f-fd10-4123-9fde-f623361044de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>this.value = this.value.replace(/[^0-9]/g, '').replace(/(\..*)\./g, '$1');</value>
      <webElementGuid>bba607ae-a5b6-4a10-8054-226d4a1c467a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>validateNomor()</value>
      <webElementGuid>e9b382b0-0f6c-4f4f-bd33-b6c086d6e5bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return allowOnlyNumbers(event)</value>
      <webElementGuid>10e5e534-4125-4f29-b29b-bbeaa144f9c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>no_handphone</value>
      <webElementGuid>7ecf08f7-0aff-4147-aef0-27261121b79b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>No. Handphone</value>
      <webElementGuid>887206af-64d3-4c18-a5af-ad03aac41307</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;no_handphone&quot;)</value>
      <webElementGuid>04764e4f-6ed0-4ec5-a09b-c502a0093226</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='no_handphone']</value>
      <webElementGuid>77dbe49c-926e-47c6-8d06-e58f0f92bf9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='data-diri']/div/div[2]/div[2]/div/div/div[2]/input</value>
      <webElementGuid>43952da7-a9f1-4a15-83cd-62f7f50bffe1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>f8a1ea98-64b0-4e69-9000-0bbf4232cedc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'no_handphone' and @type = 'text' and @name = 'no_handphone' and @placeholder = 'No. Handphone']</value>
      <webElementGuid>068c37e8-0b95-4c07-9f50-c17a13586c23</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
