<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Lupa Password</name>
   <tag></tag>
   <elementGuidId>a4289b02-551a-42dd-808c-f30b8a452621</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.auth-link.text-login</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='login-form']/div/div/div[4]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0181feb8-9df9-4b7c-9fb2-a836947a4d2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://dev.awh.co.id/area-undangan/lupa</value>
      <webElementGuid>8b5f12d7-2021-4b11-8822-7e6ec265e375</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>auth-link text-login</value>
      <webElementGuid>edaf9eba-c122-46ae-a541-f06fe46b967d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lupa Password?</value>
      <webElementGuid>3e020033-4e49-4bef-a4d6-eb5e73666559</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login-form&quot;)/div[@class=&quot;contact_form-container&quot;]/div[1]/div[4]/a[@class=&quot;auth-link text-login&quot;]</value>
      <webElementGuid>52dc443b-919a-4e3a-8ea3-3fa12fa36643</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='login-form']/div/div/div[4]/a</value>
      <webElementGuid>ff842003-1f1b-4781-9399-b174003c4a01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Lupa Password?')]</value>
      <webElementGuid>3d953b25-a374-42d2-84ea-d75b051c74d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tetap Masuk'])[1]/following::a[1]</value>
      <webElementGuid>3f29b889-0f4f-463d-998c-f86d2d0022ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login'])[1]/preceding::a[1]</value>
      <webElementGuid>05715db1-df44-4d3c-96cd-f6ab0e83b599</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Lupa Password?']/parent::*</value>
      <webElementGuid>4be01319-79c9-4286-a7ce-692da83ffff4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://dev.awh.co.id/area-undangan/lupa')]</value>
      <webElementGuid>e3842025-96af-407f-8dab-60cf1c713e1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/a</value>
      <webElementGuid>04286a05-3fe3-458f-aa84-2e3b763f8731</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://dev.awh.co.id/area-undangan/lupa' and (text() = 'Lupa Password?' or . = 'Lupa Password?')]</value>
      <webElementGuid>69ec83be-15ce-40ad-8937-4eed0e14c518</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
