<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Tetap Masuk</name>
   <tag></tag>
   <elementGuidId>2413ab11-ebec-49e9-ab36-38bad05fa5a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>label[name=&quot;force_login&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@name='force_login']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>40420869-ab3d-4dca-a646-d75bb4719449</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-login</value>
      <webElementGuid>9d1b681f-c32a-4dba-a735-aa58bd3f5441</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>force_login</value>
      <webElementGuid>5f580fee-8f59-4dc8-acb6-ed5f318a95b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>force_login</value>
      <webElementGuid>10e232dd-3e5e-4a7b-9bef-15d1eed6d415</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tetap Masuk</value>
      <webElementGuid>366c608f-e252-46c0-b53f-a4c5150225a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login-form&quot;)/div[@class=&quot;contact_form-container&quot;]/div[1]/div[3]/label[@class=&quot;text-login&quot;]</value>
      <webElementGuid>c1bd505f-d701-4ef2-9128-e2ff414a1c6b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@name='force_login']</value>
      <webElementGuid>45d5298f-83d2-4c21-b79a-cec8773239df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='login-form']/div/div/div[3]/label</value>
      <webElementGuid>ee82d943-c1a7-41f3-b09a-1e1793565006</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lupa Password?'])[1]/preceding::label[1]</value>
      <webElementGuid>11527998-b629-4222-b5ab-5dd974cdf655</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login'])[1]/preceding::label[1]</value>
      <webElementGuid>31a45cfe-79cb-47dc-86b8-863a20dfce45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Tetap Masuk']/parent::*</value>
      <webElementGuid>85c4dbce-5e62-4b4e-aabc-2da70562ca17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label</value>
      <webElementGuid>a966a3e0-7fc0-45d3-9622-23d2091b761e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@name = 'force_login' and (text() = 'Tetap Masuk' or . = 'Tetap Masuk')]</value>
      <webElementGuid>c25c4e50-1731-46f0-ba07-5ee449596935</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
