<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Form input no urut tiket max</name>
   <tag></tag>
   <elementGuidId>319b13b2-aa22-466f-8abd-62f587ad8f3a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#loket_max_sequence</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='loket_max_sequence']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a396b6bc-7e95-47ec-a251-bf72b5eb5d37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>6de689aa-a962-4af9-85b7-a6a4be56327e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>loket_max_sequence</value>
      <webElementGuid>0d569022-b2f1-4b24-babb-5c4941895f58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>f3974032-36a9-42e6-9b18-b55187bc97bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>9f33a280-3d7e-4623-9b4e-fb734d302fa4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan angka</value>
      <webElementGuid>fa8a94d7-e99a-4b90-b050-366312c2fd5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;loket_max_sequence&quot;)</value>
      <webElementGuid>6ef7e84c-5bfb-436c-9ba2-084e5b8d107c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='loket_max_sequence']</value>
      <webElementGuid>1178115e-15a1-409c-b904-6a7c1823932b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-scan-nonactive-bacth']/div/div/div[2]/div/div[2]/div[3]/div/input</value>
      <webElementGuid>ccdba9c8-de8e-48ef-99a1-6dcfae7924c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>dc0ff353-8365-403f-88d9-80810c07b061</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'loket_max_sequence' and @type = 'number' and @placeholder = 'Masukkan angka']</value>
      <webElementGuid>1c5c52f3-1829-4d7c-9ff6-7e667738686c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
