<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Form Input aktivasi tiket by nomor kode batch</name>
   <tag></tag>
   <elementGuidId>bf2b4c64-3133-4c85-b0b7-898e07fc7f7b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#guest_batch_code</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='guest_batch_code']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>334b7f85-9a7a-42c1-9578-c0a0f0a5080c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>guest_batch_code</value>
      <webElementGuid>c3dbd3e1-10c0-4c66-9f35-2fe2ed1a8ff3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e532e83c-acab-49d2-9bdb-6c0434428d83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>56e26ba3-f087-4367-8fd3-9ded5577e593</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;guest_batch_code&quot;)</value>
      <webElementGuid>07e6bdcf-de98-45bc-8796-7ea1d63fd4a0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='guest_batch_code']</value>
      <webElementGuid>67395e81-03c9-4d82-90d1-32e1ee1ac0bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-activated-ticket-bacth']/div/div/div[2]/div/div/input</value>
      <webElementGuid>cdd262c3-92c2-424f-addb-14790a4a0375</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>da196c8c-fb78-479a-ae50-f086f21cdb6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'guest_batch_code' and @type = 'text']</value>
      <webElementGuid>f4eefffa-dcb1-4e1e-9fe7-a4cc3b728cc8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
