<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Form input no urut tiket min</name>
   <tag></tag>
   <elementGuidId>74b95ddf-3cc8-4f31-b651-cda12a42b3e8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#loket_min_sequence</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='loket_min_sequence']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cb8de951-33ec-4c74-9265-5126f209a39c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>6fd38eb4-e971-4e9e-aec7-585804bda08a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>loket_min_sequence</value>
      <webElementGuid>d1f03e70-7de1-4879-999b-f0f91c1783f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>91dbc97c-58f0-47a6-a481-0c90468105b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control mt-3</value>
      <webElementGuid>864c511b-a117-4d1a-9d2a-9c5364b63faf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan angka</value>
      <webElementGuid>e32aa7ed-066c-4895-80ce-1db5701111f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;loket_min_sequence&quot;)</value>
      <webElementGuid>3269b76b-cbd4-492d-8129-565bbe77f0c3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='loket_min_sequence']</value>
      <webElementGuid>542fbe0e-ccc7-4e7d-88f2-d986a27a7fc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-scan-nonactive-bacth']/div/div/div[2]/div/div[2]/div/div/input</value>
      <webElementGuid>38127565-084b-4e2f-85f4-a70c70675303</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div[2]/div/div/input</value>
      <webElementGuid>f393095a-4ad6-4e86-a800-0fe9eb6c76a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'loket_min_sequence' and @type = 'number' and @placeholder = 'Masukkan angka']</value>
      <webElementGuid>1eddc9a5-c6a2-4509-9b7b-7062cd2e948b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
