<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Form input kode batch kirim tiket</name>
   <tag></tag>
   <elementGuidId>8d3f1067-e41f-445a-b7aa-1ab857634d43</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#loket_guest_batch_code</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='loket_guest_batch_code']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>827f4b2d-86ec-4efa-9217-fc7e6661597f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>loket_guest_batch_code</value>
      <webElementGuid>7a571c25-d9f4-41a5-bef1-9ad40d95c70c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>cb0dbe83-e9b5-4b64-a1a2-9fd1a2f829a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>a5cb5aa7-2847-40e6-bb61-b5a433b6c1bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;loket_guest_batch_code&quot;)</value>
      <webElementGuid>59b66a55-9b69-42b1-b931-d2f40648d687</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='loket_guest_batch_code']</value>
      <webElementGuid>6ec158c0-a89d-4972-8d8c-12580c38b05d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-scan-nonactive-bacth']/div/div/div[2]/div/div/div/input</value>
      <webElementGuid>b016df86-8525-49ae-ab85-d1ab44c553d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/input</value>
      <webElementGuid>3181c423-2843-4265-b792-a2cac72b1207</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'loket_guest_batch_code' and @type = 'text']</value>
      <webElementGuid>5a0f90db-57fe-483d-92f8-a901f4a04b4e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
