<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Tombol_logout</name>
   <tag></tag>
   <elementGuidId>7fdb1a6c-1283-4985-87a9-6830e1665f10</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[contains(@src,'https://dev.awh.co.id/area-undangan/assets/scanqr/img/tiket/dusunbambu/logout.png')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.icon-logout</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>f6fa84b8-bbea-4fad-967a-e32df17feef5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://dev.awh.co.id/area-undangan/assets/scanqr/img/tiket/dusunbambu/logout.png</value>
      <webElementGuid>8b26f1a4-a09d-4755-b324-39f0151c8529</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-logout</value>
      <webElementGuid>6329175a-32b2-4901-b921-d9888812db57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;container-scroller&quot;]/nav[@class=&quot;navbar navbar-expand-lg navbar-light bg-light&quot;]/nav[@class=&quot;navbar navbar-expand-lg navbar-light bg-light d-flex justify-content-between w-100&quot;]/div[@class=&quot;d-flex justify-content-center align-items-center&quot;]/div[2]/img[@class=&quot;icon-logout&quot;]</value>
      <webElementGuid>195aab70-7248-450a-937e-dc0d6845c102</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://dev.awh.co.id/area-undangan/assets/scanqr/img/tiket/dusunbambu/logout.png')]</value>
      <webElementGuid>53311254-4ded-4347-b625-8f7fa33036b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/img</value>
      <webElementGuid>d187a555-fe0e-48a3-b7e9-5c24d4db199f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://dev.awh.co.id/area-undangan/assets/scanqr/img/tiket/dusunbambu/logout.png']</value>
      <webElementGuid>2644ea1c-394b-46d2-8954-dfeb3aab7f54</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
