<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Tombol_Refresh</name>
   <tag></tag>
   <elementGuidId>2eaf5ad0-e1be-4e7e-8c37-3bd2fc58c1d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[contains(@src,'https://dev.awh.co.id/area-undangan/assets/refresh.png')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.icon-refresh</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>22e69519-717c-4c52-b9d3-eb6e49f0c59a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://dev.awh.co.id/area-undangan/assets/refresh.png</value>
      <webElementGuid>497c556c-fcb0-41fa-bf63-b7410a04d6d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-refresh</value>
      <webElementGuid>4f16bbf2-3059-4713-8b99-297bd5e25f05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;container-scroller&quot;]/nav[@class=&quot;navbar navbar-expand-lg navbar-light bg-light&quot;]/nav[@class=&quot;navbar navbar-expand-lg navbar-light bg-light d-flex justify-content-between w-100&quot;]/div[@class=&quot;d-flex justify-content-center align-items-center&quot;]/div[1]/img[@class=&quot;icon-refresh&quot;]</value>
      <webElementGuid>946d496d-9ddc-4312-8488-fd7f5c4f2915</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://dev.awh.co.id/area-undangan/assets/refresh.png')]</value>
      <webElementGuid>1dcb9573-4d87-4350-a31b-34692e7e40ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/img</value>
      <webElementGuid>97063381-5e1e-4ce6-bf1e-35e23ea20fc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://dev.awh.co.id/area-undangan/assets/refresh.png']</value>
      <webElementGuid>04764f7c-ffde-414d-968e-d5d898af6e71</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
