<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Tombol Pagination</name>
   <tag></tag>
   <elementGuidId>f05ad78e-6153-48ac-8fd3-b4ea226c73e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='generate-qr']/div/div/div[3]/div[3]/button[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.nextBtn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e9ce3ae6-f397-4f0a-93f3-f6a5958a334b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nextBtn</value>
      <webElementGuid>87ca46cf-d882-472c-a9e6-d550cf8ceb84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>></value>
      <webElementGuid>0e074eac-5fd8-45b1-9395-8d6c7cafe6ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;generate-qr&quot;)/div[@class=&quot;p-2&quot;]/div[@class=&quot;text-center&quot;]/div[3]/div[@class=&quot;pagination-controls&quot;]/button[@class=&quot;nextBtn&quot;]</value>
      <webElementGuid>7a0556a9-59c0-40ab-97dc-4079562b20e5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='generate-qr']/div/div/div[3]/div[3]/button[2]</value>
      <webElementGuid>ca569770-6e86-4474-b965-125e3db57239</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='&lt;'])[1]/following::button[1]</value>
      <webElementGuid>6147114c-03cf-4e80-ba51-5e0986955a80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tiket'])[16]/following::button[2]</value>
      <webElementGuid>9b297ed9-ad00-41bc-821f-773abafe37c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AWH'])[1]/preceding::button[1]</value>
      <webElementGuid>d0dfa859-310a-4b32-8fb5-12cbaca21f7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='>']/parent::*</value>
      <webElementGuid>0338fea6-1d67-44c3-8367-4302c1525f2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>4fa2a594-5357-4cf7-bff2-76b3eab5b823</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = '>' or . = '>')]</value>
      <webElementGuid>cce32fe7-29ce-4bcd-8496-4e604ad5b282</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
