<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Tombol_Pilih_Jenis Tiket</name>
   <tag></tag>
   <elementGuidId>858d0453-fe0a-4ed3-83a8-2cdfb5d02452</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='guest_category_id']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#guest_category_id</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>bcc8c2ec-8526-4662-ad80-2c315ebe584b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>guest_category_id</value>
      <webElementGuid>f1e08e54-204b-4371-a01e-8ee1aa5ede77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>guest_category_id</value>
      <webElementGuid>4c84f290-5776-427e-8fe6-e4d40bdee33b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>c5367f11-d26a-4600-8d04-8ca80b22bc22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                            GRATIS
                                                            P1
                                                            P3
                                                    </value>
      <webElementGuid>ceb97814-da91-4326-8cd9-98b1ecfc5f3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;guest_category_id&quot;)</value>
      <webElementGuid>d6bb1911-3820-4c4e-abf3-ae68ec65d42a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='guest_category_id']</value>
      <webElementGuid>2c6a1c32-67a0-477f-b8a4-dec954542222</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-add-']/div/div/div[2]/form/div/select</value>
      <webElementGuid>e6836080-f924-4a5e-ad01-be3e8039d5cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Warna Gelang'])[1]/following::select[1]</value>
      <webElementGuid>f7031bc6-a3c6-4e3c-89be-fa3510882994</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tambah tiket yang akan dicetak'])[1]/following::select[1]</value>
      <webElementGuid>3fcb45a5-27c6-4190-a845-33423a9ba271</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total Tiket'])[1]/preceding::select[1]</value>
      <webElementGuid>6849ebe1-40d6-4271-bea0-b91f04671a65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Simpan'])[1]/preceding::select[1]</value>
      <webElementGuid>668bb70b-b30b-4676-9880-29bf1030f00f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>76dacb71-c271-41ae-a9b2-947c0adf0d9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'guest_category_id' and @name = 'guest_category_id' and (text() = '
                                                            GRATIS
                                                            P1
                                                            P3
                                                    ' or . = '
                                                            GRATIS
                                                            P1
                                                            P3
                                                    ')]</value>
      <webElementGuid>27d0e5a6-50b2-4cc4-b415-e53688ebd044</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
