<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Keranjang Belanja</name>
   <tag></tag>
   <elementGuidId>033d681a-0977-4e56-afcb-3d3c9f516dd6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@onclick='openSidebar()']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.btn-icon.cart.p-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>165b170f-28b5-4c98-94a3-2559a14330b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://pos.awh.co.id/assets/icons/add-to-cart.png</value>
      <webElementGuid>1a0d26d6-fd3a-4511-902a-4929625ff358</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-icon cart p-1</value>
      <webElementGuid>44d7562a-c030-48fc-91f0-4b54aea71848</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>openSidebar()</value>
      <webElementGuid>fe677baf-7bb8-4092-a904-7fd5983ef760</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;col-lg-12 col-md-12 col-12 mobile&quot;]/div[@class=&quot;container-fluid mb-5&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-2 col-md-2 col-2 position-relative&quot;]/img[@class=&quot;btn-icon cart p-1&quot;]</value>
      <webElementGuid>18fd490f-5ec3-4937-9276-906036219f4b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@onclick='openSidebar()']</value>
      <webElementGuid>1d344644-7b1a-41b0-bd51-5dae654a9b3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://pos.awh.co.id/assets/icons/add-to-cart.png')]</value>
      <webElementGuid>1f319147-c1b3-4af2-8972-05a1bd2b2b18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/img</value>
      <webElementGuid>39ae5fe4-26f5-44ac-9849-4dcc94c43c3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://pos.awh.co.id/assets/icons/add-to-cart.png']</value>
      <webElementGuid>b27f19ba-1354-4e85-9e93-f27fee76c391</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
