<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Form pilih golongan darah peserta</name>
   <tag></tag>
   <elementGuidId>ccb53c1c-c02a-45a7-96e5-0b065f004486</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#exampleSelect</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='exampleSelect']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>ad21f7c3-948b-47d1-9318-8e5cb1f02151</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>blood_type</value>
      <webElementGuid>84a6ecde-e863-4bd8-9483-8b4bac2c1b7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>dab6666c-faee-498a-9475-9290e2b3b59a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>exampleSelect</value>
      <webElementGuid>07ffb6be-16c4-4c1a-91f3-4e51895c6c22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                A+
                                A-
                                B+
                                B-
                                AB+
                                AB-
                                O+
                                O-
                            </value>
      <webElementGuid>53e4b127-a3af-4f67-8a23-f310e7d8220f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;participantForm0&quot;)/div[@class=&quot;card-body&quot;]/div[@class=&quot;form-group&quot;]/select[@id=&quot;exampleSelect&quot;]</value>
      <webElementGuid>5af37d2b-0ae4-4182-b2c3-06c9f2be0edc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='exampleSelect']</value>
      <webElementGuid>6ab3a85b-db15-4331-aea1-47713dc037c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='participantForm0']/div/div[16]/select</value>
      <webElementGuid>a91f4d3d-9bae-4dee-ac4d-74f52f4e8181</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your Blood Type*'])[1]/following::select[1]</value>
      <webElementGuid>db64e41c-8f82-4ce3-88ec-c9daab0e4357</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Address harus diisi!'])[1]/following::select[1]</value>
      <webElementGuid>b76c2c52-7ad2-48e8-b82f-2df3cf33ca6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Boold Type harus diisi!'])[1]/preceding::select[1]</value>
      <webElementGuid>4a208ae0-0f08-4f97-bf9a-7ad6966c55a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Riwayat Penyakit'])[1]/preceding::select[1]</value>
      <webElementGuid>d15360a1-74e9-4f9c-a08c-c0a1c47fa99c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[16]/select</value>
      <webElementGuid>f497ff53-cf71-4d13-a3ee-2851b9c40d3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'blood_type' and @id = 'exampleSelect' and (text() = '
                                A+
                                A-
                                B+
                                B-
                                AB+
                                AB-
                                O+
                                O-
                            ' or . = '
                                A+
                                A-
                                B+
                                B-
                                AB+
                                AB-
                                O+
                                O-
                            ')]</value>
      <webElementGuid>b10eb737-61a5-4db2-a7ae-a0a2fbdbb3d9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
