<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Form input ukuran baju</name>
   <tag></tag>
   <elementGuidId>e30e107d-fca5-4090-a307-3abdfdcb95ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//select[@id='exampleSelect'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>b7d760ac-4223-45c3-b3d3-4600d30d35a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control jerseySizeSelect</value>
      <webElementGuid>20433458-f17b-4cbc-9ae4-17de4be39944</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>jersey_size</value>
      <webElementGuid>b2e26bb0-ff93-4969-ae26-19edee4fa071</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>exampleSelect</value>
      <webElementGuid>87588d63-7038-428c-8de3-8691346e7d44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select Size3XSXXSXSSMLXLXXL</value>
      <webElementGuid>3a862286-0bc0-47f5-b4e7-73fb6725f375</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;participantForm0&quot;)/div[@class=&quot;card-body&quot;]/div[@class=&quot;form-group&quot;]/select[@id=&quot;exampleSelect&quot;]</value>
      <webElementGuid>69cab4ec-19cf-4633-9fe1-2e9481978032</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//select[@id='exampleSelect'])[3]</value>
      <webElementGuid>264a257f-0be3-4814-b9b0-cc9ce9b0e285</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='participantForm0']/div/div[19]/select</value>
      <webElementGuid>197fae01-2b40-4f4c-acf8-4fb9f47bbdf9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ukuran Jersey*'])[1]/following::select[1]</value>
      <webElementGuid>2cecb8b8-d8ee-4397-8414-580f0b1bc110</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Note: All the manual measurements are in centimeters, allow 1 - 1.5 cm normal error.'])[2]/following::select[1]</value>
      <webElementGuid>affb8560-d2bc-4de9-b584-027761c58f86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ukuran Baju Type harus diisi!'])[1]/preceding::select[1]</value>
      <webElementGuid>ca497206-2df6-44be-b143-29724f03d171</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Emergancy Contact Email 1'])[1]/preceding::select[1]</value>
      <webElementGuid>4ef1517d-d717-4482-a5dc-40208418e14f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[19]/select</value>
      <webElementGuid>cb8e29b7-f9c1-458d-afdc-5fcb9a0a262e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'jersey_size' and @id = 'exampleSelect' and (text() = 'Select Size3XSXXSXSSMLXLXXL' or . = 'Select Size3XSXXSXSSMLXLXXL')]</value>
      <webElementGuid>121bf253-cf7b-42c2-a8b7-3230aa6ce9e9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
