<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Tombol cek kode referal komunitas</name>
   <tag></tag>
   <elementGuidId>58b49cfc-7e69-48d3-ab5e-48a7f14d153a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='saveReferral']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#saveReferral</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>db5d076a-a28d-4096-b222-634e549b7751</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5d5f0cce-a4d5-4cc8-b485-51af4f88cffa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary mt-2</value>
      <webElementGuid>128abb05-2cc4-49fb-bd11-345ace0f67db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>saveReferral</value>
      <webElementGuid>ca993486-2290-4798-a07e-8c1422964e47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cek Kode Referal</value>
      <webElementGuid>4b2aff6b-8ffb-4bcf-aaf8-c852447d4db8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;saveReferral&quot;)</value>
      <webElementGuid>ca1d0cfb-ba54-42e2-9888-2f6ee20a68f8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='saveReferral']</value>
      <webElementGuid>4686a198-00cc-47f8-a955-aa98e6bd12d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='komunitasModal']/div/div/div/div/button</value>
      <webElementGuid>04a58f5a-904d-48d6-99ab-050059f8f8a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kode Referal'])[1]/following::button[1]</value>
      <webElementGuid>b66bfda0-c5c9-4fb3-8101-5181c6a5c4cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Syarat &amp; Ketentuan'])[1]/preceding::button[1]</value>
      <webElementGuid>fe9ff5c2-94e1-45ea-acf6-02bc2bba4b78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tutup'])[1]/preceding::button[2]</value>
      <webElementGuid>963db8aa-d9b8-4c89-9a0c-edf07500d3db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Cek Kode Referal']/parent::*</value>
      <webElementGuid>5aa39f48-14cb-412b-bace-1506d20f1fb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>3e3b04da-2aee-49d5-9c10-6ff4635a46c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'saveReferral' and (text() = 'Cek Kode Referal' or . = 'Cek Kode Referal')]</value>
      <webElementGuid>9bbe0c95-fc39-4f12-a622-9e16237bb99d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
