<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Tombol partisipan anak</name>
   <tag></tag>
   <elementGuidId>d8654eda-3d5f-4187-b2dd-577c42f17dcf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnParticipant2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='btnParticipant2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6bf29635-8ce2-4a35-a341-1a790be2ff3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-light btn-participant btn-participant-3</value>
      <webElementGuid>792401e4-9d2f-4938-9269-9650ef8db186</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnParticipant2</value>
      <webElementGuid>0a8289f5-78de-4052-aa9e-c5aa5761bfee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>switchForm(2)</value>
      <webElementGuid>254af910-2af4-43d6-91e6-51a57a8394e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Anak</value>
      <webElementGuid>1e48d14b-0e8a-425a-a250-872f3c67ec69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnParticipant2&quot;)</value>
      <webElementGuid>a1606544-4902-4b8a-a97c-bc317bca06a3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='btnParticipant2']</value>
      <webElementGuid>57840a13-c2c3-4308-a551-ba9050ced1db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ibu'])[1]/following::div[1]</value>
      <webElementGuid>b652fbfd-0807-445f-9713-916f657cb759</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ayah'])[1]/following::div[2]</value>
      <webElementGuid>a812d22e-024b-430c-88d5-6c45b17438cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Informasi Pemesanan Anda'])[1]/preceding::div[1]</value>
      <webElementGuid>d5417e24-7151-4672-af8d-4277c9931bdc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Race 10k'])[1]/preceding::div[1]</value>
      <webElementGuid>3fdd506e-146e-4218-9cff-465f3ff8788c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Anak']/parent::*</value>
      <webElementGuid>a8ac2414-80fe-4381-b978-766f56ba5893</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div[3]</value>
      <webElementGuid>e8aeb8f9-9b66-4820-bd5a-c5ef30c95634</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'btnParticipant2' and (text() = 'Anak' or . = 'Anak')]</value>
      <webElementGuid>b9938792-45fc-43ae-92db-9ac3020e7de1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
