<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Tombol partisipan Ibu</name>
   <tag></tag>
   <elementGuidId>b6c3bd6d-7c92-4baf-8b0d-74cd5eeaf3f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnParticipant1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='btnParticipant1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a4c72b15-e87a-4c45-9573-92973bd1df8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-light btn-participant btn-participant-2</value>
      <webElementGuid>fc0e0152-ff14-4a9c-908b-b2518e89f261</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnParticipant1</value>
      <webElementGuid>bca8a7c0-d4c4-46fb-a00e-ae451714a42d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>switchForm(1)</value>
      <webElementGuid>f40cc6dc-89f5-4c42-abde-963593d9f36d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ibu</value>
      <webElementGuid>857ac3d0-0afd-4e8f-a5fd-64c9ae14ce71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnParticipant1&quot;)</value>
      <webElementGuid>a1cbe2fb-7739-4c0a-90c1-365ab3bde219</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='btnParticipant1']</value>
      <webElementGuid>8e68ae38-ce25-470d-ba53-8cad6e242f61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ayah'])[1]/following::div[1]</value>
      <webElementGuid>afd68e14-e2eb-4ec6-a5df-450395f1e0b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Phone Number harus diisi!'])[6]/following::div[5]</value>
      <webElementGuid>abead652-692e-4b61-b003-c0e7207e9eed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Anak'])[1]/preceding::div[1]</value>
      <webElementGuid>a661af13-1036-48f7-88ba-6f1631eb7b48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Informasi Pemesanan Anda'])[1]/preceding::div[2]</value>
      <webElementGuid>d1455caa-37f3-402a-b169-a325108d7023</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ibu']/parent::*</value>
      <webElementGuid>4b858568-cced-48ea-9014-d1663606de60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div[2]</value>
      <webElementGuid>a1139c9c-be3f-4667-8e76-5daf8fcbd58a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'btnParticipant1' and (text() = 'Ibu' or . = 'Ibu')]</value>
      <webElementGuid>20ce9674-fbdc-4f1b-926b-9f982dd1af94</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
