<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Form input kode bacth</name>
   <tag></tag>
   <elementGuidId>87e55e9e-52ca-4460-b4c7-d4dab9d5dcf1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='order_guest_batch_code']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#order_guest_batch_code</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>67578f6f-7f48-48bf-9012-b1bd88f9d1cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>order_guest_batch_code</value>
      <webElementGuid>fd133733-bc27-4da2-9baf-affe0fdacacd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>10327e86-f3fb-40f7-abc0-efb336906b74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan kode batch</value>
      <webElementGuid>cba5ede0-c53e-4755-9f6b-bc74bcbda400</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>97623c3e-deb5-4882-8a0a-8e37a552a566</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;order_guest_batch_code&quot;)</value>
      <webElementGuid>f692b8f8-60e0-4d82-9aef-3396eff80e4f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='order_guest_batch_code']</value>
      <webElementGuid>dabe77b1-db56-4366-a6ef-c0eda62fdb33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-scan-order-bacth']/div/div/div[2]/div/div[2]/input</value>
      <webElementGuid>3c59efe5-f879-4d04-bb2b-5ee732fa2960</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[2]/div/div[2]/input</value>
      <webElementGuid>71abb09a-13ad-4ae0-a2aa-311a392bb6ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'order_guest_batch_code' and @type = 'text' and @placeholder = 'Masukkan kode batch']</value>
      <webElementGuid>c8a87bce-2057-4315-989a-2f8c41584c8b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
