<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Form input nomor urut min</name>
   <tag></tag>
   <elementGuidId>63958ada-ff62-4e85-9a93-2b7dab1a7c1b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='order_min_sequence']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#order_min_sequence</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7507392d-7cc6-4fef-95ce-efb1ffcd2ea1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>order_min_sequence</value>
      <webElementGuid>ef307c67-8762-4c1f-89fe-9611ba419b3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>c135bdbc-9f01-4d45-94b7-2da8f0cbf0aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>39420a72-f672-4630-a00e-8b0e18720c86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control mt-3</value>
      <webElementGuid>83ba6728-af27-4c15-8b38-917aa42a2c37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan angka</value>
      <webElementGuid>a692b703-0422-4920-a173-b142b914cb11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;order_min_sequence&quot;)</value>
      <webElementGuid>e1365aa1-67ac-4554-885f-fb7b98c0b6c5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='order_min_sequence']</value>
      <webElementGuid>b7483103-ac74-4006-b38f-5e7515d5f47e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-scan-order-bacth']/div/div/div[2]/div/div[3]/div/div/input</value>
      <webElementGuid>ffbe85cd-382e-461f-8c2c-ab8362df6f4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[2]/div/div[3]/div/div/input</value>
      <webElementGuid>de313dab-03a9-4319-9a85-b3b6f77ed084</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'order_min_sequence' and @type = 'number' and @placeholder = 'Masukkan angka']</value>
      <webElementGuid>47225429-b675-4f45-8dbc-a6274135bd0b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
