<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Form input nama grup order</name>
   <tag></tag>
   <elementGuidId>5e0e49da-2f92-4c60-925b-b1d7fd18b259</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='group_name_batch']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#group_name_batch</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>11334d88-cfa1-4656-a481-03d0baa0134b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4ad31f76-47ac-4a37-9d92-74fe50ad2019</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>group_name_batch</value>
      <webElementGuid>58201a9e-df52-4b68-b112-c1dbeea3889e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>f7a35527-ba11-4d94-860d-5a2c751d327a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan nama grup</value>
      <webElementGuid>1b94a19b-701d-4e36-87cb-e2e39408a3e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;group_name_batch&quot;)</value>
      <webElementGuid>164acd28-a6e4-487d-9e46-c2ae613c5055</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='group_name_batch']</value>
      <webElementGuid>104766cb-a69f-4c3e-8c56-540cfaf2d462</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-scan-order-bacth']/div/div/div[2]/div/div/input</value>
      <webElementGuid>0560df51-622d-48bb-ad21-dc4f192e8ed1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[2]/div/div/input</value>
      <webElementGuid>50f3184d-1e85-4df7-a41a-92fb1b0c272b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'group_name_batch' and @placeholder = 'Masukkan nama grup']</value>
      <webElementGuid>25a7ce48-a34d-4aa7-b00d-29929d1eb789</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
